### ISSUE TITLE
Use WP_ENVIRONMENT_TYPE instead of Altis function

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-consent#19]
We're relying on this plugin being in an Altis context and reliant on the Altis core module for this environment type check:

https://github.com/humanmade/altis-consent/blob/master/inc/namespace.php#L35

Altis will support `WP_ENVIRONMENT_TYPE` as of v5 so we should switch to that constant.

**Comment by rmccue** [comment]
This is only a could and I think it's OK for this to rely on Altis, so closing.
