### ISSUE TITLE
Banner JS still enqueued if banner template not output

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-consent#22]
The conditional around whether to output the banner JavaScript is not the same as whether to output the banner template. This can result the following JS error due to the banner HTML not being present:

```
TypeError: document.querySelector(...) is null
```

**Comment by jazzsequence** [comment]
This should be resolved in #30 
Can you confirm @roborourke

**Comment by roborourke** [comment]
Yep, good to close out 👍
