### ISSUE TITLE
TASK: Consent module should only support client side API

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-consent#25]
## Background

A couple things came out of a discussion with the lead developer of the WP Consent API feature plugin on https://github.com/rlankhorst/wp-consent-level-api/issues/61. The points worth noting:

1. The Complianz plugin "mainly" uses the client-side API and recommends that as a solution for playing nice with caching. (https://github.com/rlankhorst/wp-consent-level-api/issues/61#issuecomment-696881029)
  i. They recommend the [`wp_listen_for_consent_change`](https://github.com/rlankhorst/wp-consent-level-api/blob/master/assets/js/wp-consent-api.js#L100) event listener to listen for consent changes.
2. The PHP component is, essentially, for backwards compatibility. He notes that a lot of WP plugins handle this sort of logic in PHP only and that "these plugins won't work very well with hard page caching." He also indicates that the Privacy team is discussing using the Consent API to store consent preferences in the user profile, which would have a PHP dependency. (https://github.com/rlankhorst/wp-consent-level-api/issues/61#issuecomment-697466359)

Given this, the Altis Consent module and documentation should be refactored/rewritten to _only_ use client-side javascript, and all PHP functionality and documentation relating to such should be removed. Additionally, while basing the Altis Consent module on the WP Consent API will still run the risk of teams using the PHP API despite the lack of documentation, we should note in the updated documentation that using the PHP functions is strongly _not recommended_ and not supported for caching reasons.

Any other thoughts?

cc @rmccue @roborourke 

## Proposed tactic

* break away from the WP Consent API feature plugin
  * before it's really integrated into core, we don't want to commit to the parts of it that we don't want, namely the PHP API.
  * it's possible, especially as it gets closer to actually being merged into core, that things will change very rapidly, and the timing of that might be difficult to manage -- especially without actual tagged releases -- that that could lead to problems on production versions of Altis
* take the WP Consent API _javascript_ API and fork that
* propose filtering the cookie name [https://github.com/rlankhorst/wp-consent-level-api/issues/62]
  * we can/should submit a PR for this as well as it's an easy change that they support 
* refactor our consent module to be based around the `wp_listen_for_consent_change` listener and move everything to javascript
* if we need to, we can create custom template tags (like XB and a client's Geolocation blocks), but Ryan doesn't think that's necessary right now

## Acceptance Criteria

- [x] remove dependency on WP Consent API feature plugin
  - [x] create our own forked repository for the javascript API only
    - we will need to watch to make sure any changes to the upstream repo are carried over
    - we may be able to use the existing packagist package that I had created originally for the consent api
- [x] new consent module should include wrappers for all the `wp_` functions, so we can more easily port changes over later
- [x] update front-end components to use new event listener-based API
- [x] remove our own PHP API functions
- ~remove PHP documentation (maybe just unpublish/un-link)~ split out into https://github.com/humanmade/altis-consent/issues/26

**Comment by roborourke** [comment]
Cheers @jazzsequence.

I agree 100% that we should only provide the client side JS here. Given that it's a single file and somewhat stable it might just be easier to copy that directly into this plugin for now and ditch the composer dependency on the proposed plugin.

I'd be happier not having the PHP portion of the API there at all unless you feel that the functions it provides for registering and categorising cookies are useful for building out UI components.

We can of course change tack and write our own solution based off the wrapper you have around the `wp_register_cookie_info()` function that provides a way to connect cookies by name to specific enqueued scripts. We could perhaps do something similar to how Didomi does it:

https://developers.didomi.io/cmp/web-sdk/third-parties/custom-integrations/no-tag-manager

We'll need to update the core module PR to do it's stuff client side too of course but I think it'll follow a similar pattern as the stuff you have right now.

Also Didomi has a really nice guide for Google Tag Manager integration - this is essentially what we'll want to provide too by pushing variables to `window.dataLayer`:

https://developers.didomi.io/cmp/web-sdk/third-parties/custom-integrations/tag-managers/google-tag-manager

**Comment by jazzsequence** [comment]
>Given that it's a single file and somewhat stable it might just be easier to copy that directly into this plugin for now and ditch the composer dependency on the proposed plugin.
>
>I'd be happier not having the PHP portion of the API there at all unless you feel that the functions it provides for registering and categorising cookies are useful for building out UI components.

That's a thing we could certainly do, but if/when it _does_ get merged into core, we'd have to deal with it anyway (I mean, we could bypass it and use our own consent solution, but we'd need to unhook everything from core). And it sounds like there's at least discussions about it in the Privacy channel (I joined, but I haven't been keeping tabs on it), which means that there's a decent possibility it will. And while I don't necessarily agree with the author that there _needs_ to be a PHP component (obviously there doesn't) I _do_ acknowledge that other plugins aren't going to adopt a fully client-side solution right away, and whatever does get merged into core _will_ inevitably have some PHP elements. 

I do like the idea of hooking into specific enqueued scripts but I wonder if that narrows the scope too much. Just like focusing on _cookies_ isn't the whole picture with regard to user consent and data privacy, I'm wondering if focusing on _scripts_ may be too narrow as well? 

Also, I'm curious about what happens if consent preferences are stored in user profiles (discussion seems to start [here](https://wordpress.slack.com/archives/C9695RJBW/p1598449944140600)). We could just not use or remove those fields (not sure the repercussions of this), but I'd worry about the additional overhead of supporting our own solution separate from (or including parts of) the solution built into core if it gets merged (e.g. maintaining our version of the API separately, making sure our overrides to user profile fields and whatever else still apply for every WP update, etc).

**Comment by roborourke** [comment]
> That's a thing we could certainly do, but if/when it does get merged into core, we'd have to deal with it anyway (I mean, we could bypass it and use our own consent solution, but we'd need to unhook everything from core).

We already do this kind of thing in a few places. Any WordPress update requires a few changes or updates to some dependencies so I'm not too worried about the work involved if/when that does happen. I guess the question here is that we don't know 100% whether the proposed plugin will make it into core without some degree of rewriting. If we eliminate the proposed plugin as a dependency for now then we're somewhat protected from any major rewrites or changes, especially while there aren't specific tags we can track on packagist.org. We might have to deactivate / disable the PHP component that does go into core in future too.

> I do like the idea of hooking into specific enqueued scripts but I wonder if that narrows the scope too much. Just like focusing on cookies isn't the whole picture with regard to user consent and data privacy, I'm wondering if focusing on scripts may be too narrow as well?

It is in some ways too narrow but keep in mind that once you have a particular mechanism in place it can also be employed in a more manual way. Ideally the needed event hooks and listeners should be added to the various scripts that set cookies themselves.

Even with a narrow focus it might provide a straightforward low effort way for handling maybe 50% of enqueued scripts. That's still a decent benefit for devs out of the box. For scripts output directly then developers could write them to use the automated mechanism manually, say if we follow the experience block method using `<template>` tags it could look like this:

```
<template id="my-script-handle" data-consent-type="marketing">
  <script src="https://3rdparty.com/ads.js"></script>
</template>
```

Then our script would just need to look at those tags, check the consent type and inject the contents of the template into the active DOM.

I made a quick codepen example here: https://codepen.io/sanchothefat/pen/BaKeVov

> Also, I'm curious about what happens if consent preferences are stored in user profiles (discussion seems to start here). We could just not use or remove those fields (not sure the repercussions of this), but I'd worry about the additional overhead of supporting our own solution separate from (or including parts of) the solution built into core if it gets merged (e.g. maintaining our version of the API separately, making sure our overrides to user profile fields and whatever else still apply for every WP update, etc).

I think we'll cross this bridge when we come to it, but when it comes to user profiles presumably they'll be logged in at which point we're less concerned with caching. I would still be hesitant to support checking for cookies in PHP and instead maybe pass those preferences to our front end script. Maybe the front end script for WP would be updated to use an API endpoint to set those preferences. All that remains to be seen though so I don't think it should hold us back necessarily.

**Comment by jazzsequence** [comment]
@roborourke @rmccue Is there anything I missed in the proposed tactic and acceptance criteria above from our conversation this morning/yesterday?

**Comment by roborourke** [comment]
> if we need to, we can create custom template tags (like XB and a client's Geolocation blocks), but Ryan doesn't think that's necessary right now

Yeah on this topic my proposal was over engineering it a bit. Would be functional but if we literally only need to control when JS scripts are loaded and nothing else we can take the approach of building up a list of those scripts and the consent they require then inject them into the DOM dynamically if we have consent or when we get consent. Think we can handle that idea in a separate issue and PR as it needs some more in-depth thought.

> create our own forked repository for the javascript API only

I was thinking the JS could just live in this repo to keep things more manageable. What are the benefits you're thinking of for putting the JS in it's own repo?

Rest of the acceptance criteria looks good to me 👍

**Comment by jazzsequence** [comment]
> What are the benefits you're thinking of for putting the JS in it's own repo?

I guess my thought was using the `altis/consent-api` package I originally created in Packagist and repurposing that for our fork of the javascript so that updates to the _source_ could be ported over to our forked version separately from the consent module. That way we don't need to update the consent module if the only thing that's changed is the javascript API. 

Also, @rmccue mentioned using wrappers around the WP Consent API functions (like `wp_get_consent`), and having a separate package for the JS API seems like a clearer distinction of "this is ours, this is theirs" and why the wrapper functions exist.

**Comment by roborourke** [comment]
I see, so commit the changes to remove the PHP component and just deliver the JS from there, then merge upstream updates? That might get tricky but doable 🤔 

We'd still potentially have to update the wrapper functions and maybe other elements in this repo every time `altis/consent-api` was updated. On the other hand it might stand us in better stead around core merge time...

Personally I still feel like it'd be creating more work to split them right now. Plus I'm reluctant to have a requirement for loading 2 JS files when 1 would do but if we use wrapper functions it seems like that's what we'd end up anyway.

Keen to get you thoughts there @rmccue

**Comment by rmccue** [comment]
> Yeah on this topic my proposal was over engineering it a bit

Just want to be clear: my opinion is that it's over-engineering _for the first version_. It might turn out to be a great API that we want to support in the future, but let's iterate towards it based on needs.

As for the JS side of things, my opinion is that we essentially do a fork at this point, rename and own the whole API ourselves. Let's treat the WP API as a good starting point and not deviate from it for the sake of it, but also not be beholden to matching it. (Don't forget we can also influence what goes into core by providing feedback on what works and what doesn't for us!) If/when it goes into WP, we can handle making our implementation compatible with via both wrappers and also (if necessary) breaking changes that we guide users through.

We also don't know the timelines on when this would go into core, so I wouldn't be concerned about _eventually_ having two JS files instead of one. Let's focus on shipping today, evaluating usage, and iterating on that.
