### ISSUE TITLE
TASK: Consent module should only support client side API#25 (Documentation)

### ISSUE THREAD

**Issue by jennybeaumont** [humanmade/altis-consent#26]
Split off from https://github.com/humanmade/altis-consent/issues/25

- [x] remove PHP documentation (maybe just unpublish/un-link)
- [x] add new documentation for new PHP functions
- [x] add new documentation for new/updated filters
- [x] add new documentation for new javascript functions
- [x] remove documentation for WP-Consent-API javascript functions
- [x] remove documentation for WP-Consent-API PHP functions
- [x] remove documentation for WP-Consent-API filters
- [x] move documentation into the altis-consent module

**Comment by jazzsequence** [comment]
have updated the documentation for our consent module's PHP functions: https://github.com/humanmade/altis-consent/wiki/Altis-Consent-Public-Functions

**Comment by jazzsequence** [comment]
docs have all been updated here: https://github.com/humanmade/altis-consent/wiki

added a task to move/pull the docs into the actual repository
