### ISSUE TITLE
SPIKE: Investigate IAB TCF

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-consent#27]
There is a (relatively new?) standards framework created by the Interactive Advertising Bureau called the Transparency & Consent Framework. 

https://iabeurope.eu/transparency-consent-framework/
https://iabeurope.eu/wp-content/uploads/2019/08/TCF-Fact-Sheet_General.pdf

We should do some discovery on this framework and see where we can support it as it seems to be becoming a standard for consent management platforms, particularly in Europe.

Timebox: 2 days

**Comment by jazzsequence** [comment]
> *    The Global Vendor List (GVL) managed by IAB Europe, captures and stores the registration of Vendors working with website publishers and advertisers, as well as Consent Management Platforms (CMPs) who work with publisher sites.
> * The CMP Validator is managed by IAB Europe and oversees the compliance process of CMPs participating in the TCF.

https://iabeurope.eu/transparency-consent-framework/

**Are we a Consent Management Platform?**

> Consent Management Platform (CMP) is a company or organisation that centralises and manages transparency for the consent and objection of the users of a website. The CMP can read and update the legal basis of a company that participates in the delivery of digital advertising (commonly referred to as a vendor) within a publisher’s website, app, or other digital content. Vendors declare their legal basis and purpose for accessing a user’s device or browser, or processing their personal data in the Global Vendor List (GVL).
> 
> **The CMP specifically performs the following:**
>
> * Provides users with transparency into the vendors that a publisher has chosen to work with;
> * Provides transparency into the purposes and legal basis that a vendor wishes to leverage – the names and descriptions of purposes and features can be found here 
> * Store a user’s consent signals, for example a third-party cookie, in the user’s browser and make consent information available to vendors in the TCF v2.0 TC String;
> * Ensure that consent for a purpose applies only to the vendors that have declared, via the GVL, that they use data for that purpose;

https://iabeurope.eu/tcf-for-cmps/

Based on the above, I think yes?

> CMPs must apply to IAB Europe for participation in the Framework. IAB Europe shall take reasonable steps to vet and approve a CMP’s application according to procedures adopted, and updated from time to time, by the MO (Management Organization).

https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#2_Applying_and_Registering

**...Or are we a publisher?**

> A Publisher is an operator of a website, app or other content where digital advertisements are displayed or user information is collected and used for digital advertising, measurement and analytics, or content personalisation.
> ...
> **Publishers following the TCF Policy specifically perform the following:**
>
> * Select and control vendors they want to work with;
> * Provide users with transparency into the vendors selected by the publisher, and the purposes for which they process data;
> * Request and obtain informed consent to process data, or establishing other legal bases to process data;
> * Transparently pass information relating to user choices to the ecosystem;
> * Either act as a CMP (in which case they would need to register as a CMP in the TCF) or utilise the services of a CMP registered with the TCF;
> * Support the use of data for measuring campaign effectiveness and the use of contextual advertising that requires access to user devices.

https://iabeurope.eu/tcf-for-publishers/

In either case, we'd need to register with the IAB to use the framework, either as a CMP or a publisher...

> CMPs must also register to participate in the Framework and do this by applying for an annual CMP membership with the TCF through completing the CMP application process at the CMP Portal (CMP Registration). 
> ...
> CMPs pay an annual fee of €1200. Once they have completed and passed the CMP Validation test managed by IAB Europe, they will receive an ID, sub-domain and will be listed [here](https://iabeurope.eu/cmp-list/).

https://iabeurope.eu/join-the-tcf/

There's a cost barrier here to be listed, as well as a validation process to ensure that we comply appropriately with the framework (access to the validator is by request only, presumably granted only to vendors that have applied).

If it was not obvious...

> The development of a consent solution is not a simple task and requires developers with advanced skills in JavaScript, reading/writing of cookies, network configuration and the differences between browsers, especially around security setting defaults and responsive UX rendering. CMPs must  pass the annual CMP validation test that ensures compliance with TCF specifications and Policies.

https://iabeurope.eu/tcf-for-publishers/

Implementation details: 
* Actual toolkit/suite for implementing TCF: https://github.com/InteractiveAdvertisingBureau/iabtcf-es
* Some specific implementation notes about TC Strings: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md
* Consent Management Platform API: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md
* These docs live in this repo which seems to have all the technical details: https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework

I found this way too late, but this is a webinar that talks about the TCF for vendors and CMPs (that's us!). It's ~1hr (including Q&A at the end): https://iabeurope.eu/events/iab-europes-transparency-consent-framework-tcf-v2-0-information-webinar-for-cmps-and-vendors/

**Comment by jazzsequence** [comment]
A big question is, do we integrate with a third party (like onetrust) and let them be the CMP or do we own this ourselves?

**Comment by jazzsequence** [comment]
Looking at the code and the documentation, a couple notes:

* The documentation says that `@iabtcf/cmpapi` is the only class you need as a CMP to implement TCF (at least in our context); therefore, implementing this shouldn't be too hard. https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/cmpapi
* There's much more detailed documentation and examples in the [CMP API 2.0 docs](https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20CMP%20API%20v2.md#cmp-api-v20) which seem to imply that there's more to do than simply invoke the class (functions that you need to build). There aren't a lot of real-world examples here, and searching the Complianz plugin respository came up empty as far as TCF integration (perhaps it lives in a private repo rather than the public one). As such, I expect there'd likely be some back and forth with IAB about implementation.

Therefore, I'd expect full implementation of TCF 2.0 compliance to take at least one sprint.

**Comment by jazzsequence** [comment]
@roborourke @rmccue @PriyaBhatia0210 Any thoughts?

**Comment by roborourke** [comment]
Lot to take in...

Although we do provide the latter 2 points of what a CMP does the publisher part also states they can "act as a CMP". I don't believe we're the publisher because that's the customer running on Altis. Altis will however provide some elements out of the box that enable a customer / publisher to become both a vendor (Altis Analytics) and a CMP (Consent Framework).

Because this functionality around consent is not centralised I don't think that Altis itself can be classed as either.

We're providing the tools and feature set for our customers to be both the publisher and act as the CMP it seems. I feel like it makes sense to grease the wheels of _being_ compliant without necessarily needing to pay to be listed as a CMP. The TCF seems like a useful benchmark / guide as far as we're concerned.

Basically I'm not sure how exactly the CMP registration would apply for us and how the inspection / audit for compliance would work. Is the expectation to see the centralised product or individual sites it runs on?

All that said I think it could be something we document and find ways to be compliant with, or if we go another route perhaps we can document how to use this framework to integrate with a dedicated CMP assuming it's not something all CMPs provide their own solutions for. Would be interesting to research that a bit.

There are two things both the CMP and Publishers lists call out that would make nice features too:

> Provides users with transparency into the vendors that a publisher has chosen to work with;
> Provides transparency into the purposes and legal basis that a vendor wishes to leverage – the names and descriptions of purposes and features can be found here

In my mind this might be like the cookie scanning that Complianz does and generating cookie policy pages automatically. Main challenge would be sourcing that data eg. from https://cookiedatabase.org/

:thinking-intensifies:

**Comment by rmccue** [comment]
Sounds like we're both a publisher, and a lightweight CMP. On the latter, we're providing an out-of-the-box solution that works first-party with our software, but doesn't really act as a platform for others to use.

We could integrate with CMPs, and maybe there's some sort of integration there between TCF and the way we register cookies (i.e. register your cookies with Altis Consent, automatically passed to compatible CMPs), but it sounds like a lot of work for not a huge amount of value.

IMO, the overall answer to the spike is "no, we are not TCF compliant as we aren't a dedicated CMP", and if you want TCF integration we'll consider it maybe later.

**Comment by jazzsequence** [comment]
> and how the inspection / audit for compliance would work. Is the expectation to see the centralised product or individual sites it runs on?

That's an interesting question re: how the audit actually works. I don't know. What I _do_ know is that Complianz is listed as a CMP, and they're just a plugin, too, rather than a centralized service. I expect there's some amount of code review and possibly testing (against test servers, for example) that would show that we're doing it right (or wrong).

> We could integrate with CMPs...

We could, and that might be the easy road to take, particularly if we partnered with, for example, OneTrust -- who's already listed as a registered CMP -- and just offload our TCF stuff to them.

**Comment by PriyaBhatia0210** [comment]
Only got to reading this issue today. Thanks for the elaborate research here. 

My thoughts are not too different from Ryan's. My opinion (given what I have read and understood) is that we would qualify as a CMP and might need that kind of compliance sometime in future. 

However, its low priority at the moment in the sense we'd likely need the adoption of XBs and other personalization stuff  before this feature and hence, the compliance becomes valuable to a client.
