### ISSUE TITLE
Consent banner display can be configured in code

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-consent#4]
## Description

We need a filterable conditional to determine whether or not to display the consent banner at based on arbitrary logic, that would supersede the global setting (whether to display the banner at all). 

Possible use cases for this would be if a client wanted to display the banner _only on certain pages_ or to users _only from a certain geographic region_ despite the site-defined setting.

This task is to build a conditional that is checked before rendering the banner, as well as allowing the check to be conditionally filtered based on any criteria (e.g. if we're on a specific page, or if we meet some other specific requirement handled in the filter hook).

**Comment by PriyaBhatia0210** [comment]
Just to confirm my understanding, this optionality will be available in the privacy page admin settings, right?

**Comment by jazzsequence** [comment]
The solution in the PR takes the setting that has been configured in the admin and allows it to be overridden. What actually overrides the admin setting depends on what's built using the filter. That could be an additional option on the Privacy page, or it could be something that is determined purely in the code depending on the needs of the project/client.

It's not intended to completely disregard the setting on the Privacy page, e.g. if the banner is set to display, we're not going to do a blanket override of that to just ignore what admins have set. Rather, the idea is that if there are contexts -- specific to the project -- where the banner might not be applicable (certain geographic regions, landing pages that don't do any tracking, etc), we're allowing the banner to be suppressed in the code.

I know that doesn't exactly answer your question, but does that make sense?

**Comment by PriyaBhatia0210** [comment]
HAHA... you know me well by now I guess.😁 I understand the last part which is essentially the code can suppress the banner in certain pages and I think that helps answer my question.

The reason I asked is because i was thinking of adding anything related to suppressing banners in user docs.

**Comment by jazzsequence** [comment]
Basically anything that we are offering within the consent module itself can be turned off/disabled/changed/modified/exploded/broken/reinvented/etc by other developers or development teams. Out of the box, displaying the banner is a global on/off. But if a more bespoke solution is needed (like display the banner on certain pages or to certain visitors) that can be done as well with the filters.

**Comment by PriyaBhatia0210** [comment]
Got it! Thanks!

**Comment by jazzsequence** [comment]
This is included as part of https://github.com/humanmade/altis-core/pull/92 but I also have questions about the extent to which these options are defined in the code (whether they are defaults or actually hard-coded) in https://github.com/humanmade/altis-core/pull/92#issuecomment-681151336

**Comment by jazzsequence** [comment]
The attached PR (#6) has already been merged and configuration options has been pushed back as a `should have` in https://github.com/humanmade/altis-core/issues/87. Therefore I think we can close this and revisit when we come back to this.
