### ISSUE TITLE
Bug: Allow/Deny All Cookies setting throws javascript error

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-consent#43]
Testing cookie consent banner on the platform-test site doesn't yield the banner on the front when selecting Consent Banner options as 'Allow/Deny All Cookies'. 

**Steps to reproduce:**
1. Go to Settings > Privacy > Enter all other details on the page
2. Under 'Consent Banner options' select 'Allow/Deny All Cookies'
3. Save Privacy Settings at the bottom of the page
4. Visit demo site from the top toolbar
5. It doesn't yield the consent banner.

**Acceptance Criteria:**
When I follow the above steps I should get a consent banner on the demo site exactly the way it happens when I select 'All Cookie Categories' under 'Consent Banner options'.

**Dev note:**
The issue is caused by a javascript error that is thrown when a DOM element is missing from the markup (because we aren't displaying the category options). This is most likely a regression after some of the javascript code was changed.

**Comment by jazzsequence** [comment]
This is somewhat blocking https://github.com/humanmade/altis-privacy/pull/5 so squashing early
