### ISSUE TITLE
This generates a lot of logging noise

### ISSUE THREAD

**Issue by nathanielks** [humanmade/altis-consent#49]
This warning is logged on each request:

```
PHP Warning:  The WP Consent Level API plugin must be installed and activated in /usr/src/app/vendor/altis/consent/inc/namespace.php on line 20
```

As we have healthchecks every 30 seconds, this is being logged twice a minute per container and is generating a lot of noise.

**Comment by roborourke** [comment]
I guess we can fail silently here but ideally it shouldn't be getting that far without the other script 🤔  Will check into why it it's happening.

**Comment by rmccue** [comment]
@roborourke Is this still valid, or can we close out?

**Comment by roborourke** [comment]
Hm, not actually seen it anywhere for ages, might have been fixed. Yeah we can close it.
