### ISSUE TITLE
Call to undefined function `hasContent` in the JS

### ISSUE THREAD

**Issue by roborourke** [humanmade/altis-consent#51]
There is a reference to the old function name `hasContent()` in the `Altis.Consent.getCategories()` function causing a JS error. This should be updated to `Altis.Consent.has()`.

**Comment by roborourke** [comment]
Thanks! Lets do a new patch release for this update.

**Comment by jazzsequence** [comment]
Yep, I will go through all the privacy-related stuff today and figure out if anything else needs a patch release.
