### ISSUE TITLE
Add API to register cookie documentation

### ISSUE THREAD

**Issue by PriyaBhatia0210** [humanmade/altis-consent#64]
We should automatically generate a document of all cookies registered on the site.  

**Acceptance Criteria:**
- [ ] A way to register cookies
- [ ] Name of the cookie
- [ ] Human readable description
- [ ] Duration of cookie
- [ ] Categorization
- [ ] All registered cookies should be displayed on the cookie policy page

**Comment by rmccue** [comment]
Marking this as a won't do for now.
