### ISSUE TITLE
Document how to disable consent module

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/altis-consent#69]
If a site running on Altis uses an existing, alternative consent system, right now I do not see any documentation about how to disable this module.

It does appear that filtering `altis.consent.should_display_banner` will prevent the output of JS and HTML. Is there a way to do this using `composer.json` as well? That seems to be the standard.

**Comment by roborourke** [comment]
We do need to document the module config, the simplest option for you right now @kadamwhite is to set the following config:

```json
{
	"extra": {
		"altis": {
			"modules": {
				"privacy": {
					"consent": false
				}
			}
		}
	}
}
```

You can also switch it off in the site admin settings.
