### ISSUE TITLE
Hide consent admin settings if consent is disabled

### ISSUE THREAD

**Issue by jazzsequence** [humanmade/altis-consent#72]
If Altis Consent is disabled from the config level, we shouldn't display the settings for the consent banner on the Privacy page.

**Acceptance Criteria:**
- [ ] Banner settings do not display if `altis.modules.privacy.consent` is `false`
- [ ] Privacy Settings page retains the Privacy Policy Page setting and the Cookie Policy Page setting.

![Screen Shot 2021-05-12 at 3 20 08 PM](https://user-images.githubusercontent.com/991511/118045760-96d34980-b335-11eb-9ca6-ab2ac5fbf0e2.png)

**Comment by rmccue** [comment]
Could this avoid loading the plugin entirely instead if it's disabled?

**Comment by jazzsequence** [comment]
@rmccue The consent plugin is also responsible for changing/overriding the Privacy Settings page in the admin. I suppose if we were okay with leaving the default WordPress privacy settings page and losing the Cookie Policy page creation tools, then that would be the easiest solution. That's the trade unless we want to move all that functionality out of the Consent plugin and directly into the Privacy module (which could be done).

**Comment by jazzsequence** [comment]
This is actually a non-issue. [Because we check the Privacy > Consent setting in the config](https://github.com/humanmade/altis-privacy/blob/ee261ff743fd79083ca8a3c0a77f3deb7d6bab3a/inc/consent/namespace.php#L19-L22) before loading anything consent-related, if the following config is used, none of the consent plugins will load.

```json
"extra": {
  "modules": {
    "privacy": {
      "consent": false
    }
  }
}
```

The result is that the privacy settings page goes back to the WordPress default and there's no option to define a cookie policy page, but that could be handled by the site owner some other way.

Instead, we should make sure this functionality is properly documented
