### ISSUE TITLE
Change of default cookies to show opt-in

### ISSUE THREAD

**Issue by robindevitt** [humanmade/altis-consent#88]
#### Issue/bug
While working on #85 I picked up that removing `statistics-anonymous` from the default categories, it doesn't give the user the option opt-in.

### To replicate
1. Use the following filter to make the `functional` category the only allowed by default:
```
add_filter( 'altis.consent.always_allow_categories', function () {
    return [ 'functional' ];
} );
```

2. View the site so the cookie banner displays, select Cookie Preferences.
3. You should be able to opt-in for `statistics-anonymous` cookies.

#### Expectation
When removing `statistics-anonymous` from the allowed categories, a user should be able to opt-in for the `statistics-anonymous` cookie.

**Comment by roborourke** [comment]
Seems like something we want to resolve fairly quickly too if you have time to make a PR, good spot

**Comment by robindevitt** [comment]
@roborourke Should `functional` cookies have the ability to be opt-in?

**Comment by roborourke** [comment]
Well without them it's not possible to record consent so I assume that's why the code is written the way it is. I would say they're a requirement for the feature
